use std::sync::Arc;

use axum::{
    Json, Router,
    extract::State,
    http::StatusCode,
    routing::{delete, get, post},
};
use serde_json::Value;

use crate::AppState;

pub fn create_api() -> anyhow::Result<Router<Arc<AppState>>> {
    let public_api = Router::new()
        .route("/api/v1/partners/login", post(partner_login))
        .route("/api/v1/clients/login", post(client_login));
    let private_api = Router::new()
        .route("/api/v1/partners/tickets", post(add_ticket))
        .route("/api/v1/partners/tickets", delete(delete_ticket))
        .route("/api/v1/clients/{client_id}", get(get_client_data))
        .route(
            "/api/v1/clients/{client_id}/redeem_points",
            post(redeem_points),
        );
    let router = Router::new().merge(public_api).merge(private_api);
    Ok(router)
}

pub type ApiResponse = Result<Json<Value>, StatusCode>;

pub async fn client_login(
    State(state): State<Arc<AppState>>,
    Json(user_credentials): Json<Value>,
) -> ApiResponse {
    todo!()
}

pub async fn partner_login(
    State(state): State<Arc<AppState>>,
    Json(partner_credentials): Json<Value>,
) -> ApiResponse {
    todo!()
}

pub async fn add_ticket(State(state): State<Arc<AppState>>) -> ApiResponse {
    // TODO:
    // 1. Insert the new ticket into the DB
    // 2. Extract the products and check if they can be exchanged by points
    // 3. Register the point gained from the purchase to the corresponding user
    todo!()
}

pub async fn delete_ticket(State(state): State<Arc<AppState>>) -> ApiResponse {
    // TODO:
    // 1. Delete the inserted ticket
    // 2. Delete the associated point exchanges (DB should do this automaticaly)
    todo!()
}

pub async fn get_client_data(State(state): State<Arc<AppState>>) -> ApiResponse {
    // NOTE:
    // This function should get all the data needed for the user to make the point redemtion dashboard.
    todo!()
}

pub async fn redeem_points(State(state): State<Arc<AppState>>) -> ApiResponse {
    // TODO:
    // 1. Add a redemption generated by the user to the database
    todo!()
}
