[project]
name = "sistema-tickets"
revision = "1.0"

[providers]
sops = "sops://secrets.enc.yaml"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
LAB_DB_USER = { description = "Database user for LAB server", required = true, providers = [
  "sops",
] }
LAB_DB_PASS = { description = "Database pass for LAB server", required = true, providers = [
  "sops",
] }
LAB_DB_DATABASE = { description = "Database database for LAB server", required = true, providers = [
  "sops",
] }
LAB_DB_PORT = { description = "Database port for LAB server", required = true, providers = [
  "sops",
] }
LAB_DB_HOST = { description = "Database host for LAB server", required = true, providers = [
  "sops",
] }
LAB_DB_URL = { description = "Database URL for LAB server", required = true, composed = "postgres://${LAB_DB_USER}:${LAB_DB_PASS}@${LAB_DB_HOST}:${LAB_DB_PORT}/${LAB_DB_DATABASE}" }


LAB_JWT_SECRET = { description = "JWT generation secret", required = true, providers = [
  "sops",
] }

LAB_OTP_SENDER = { description = "OTP default channel", required = true, providers = [
  "sops",
] }

EMAIL_FROM = { description = "Email address to mail from", required = true, providers = [
  "sops",
] }
EMAIL_APP_PASSWORD = { description = "Email provider app password", required = true, providers = [
  "sops",
] }

[profiles.development]
