[project]
name = "sistema-tickets"
revision = "1.0"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
LAB_DB_USER = { description = "Database user for LAB server" }
LAB_DB_PASS = { description = "Database pass for LAB server" }
LAB_DB_DATABASE = { description = "Database database for LAB server" }
LAB_DB_PORT = { description = "Database port for LAB server" }
LAB_DB_HOST = { description = "Database host for LAB server" }
LAB_DB_URL = { description = "Database URL for LAB server", composed = "postgres://${LAB_DB_USER}:${LAB_DB_PASS}@${LAB_DB_HOST}:${LAB_DB_PORT}/${LAB_DB_DATABASE}", required = true }

FARM_DB_USER = { description = "Database user for FARM server" }
FARM_DB_PASS = { description = "Database pass for FARM server" }
FARM_DB_DATABASE = { description = "Database database for FARM server" }
FARM_DB_PORT = { description = "Database port for FARM server" }
FARM_DB_HOST = { description = "Database host for FARM server" }
FARM_DB_URL = { description = "Database URL for FARM server", composed = "postgres://${FARM_DB_USER}:${FARM_DB_PASS}@${FARM_DB_HOST}:${FARM_DB_PORT}/${FARM_DB_DATABASE}", required = true }

LAB_JWT_SECRET = { description = "JWT generation secret", required = true }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
# [scopes.lab]
# secrets = [
#   "LAB_DB_DATABASE",
#   "LAB_DB_HOST",
#   "LAB_DB_PASS",
#   "LAB_DB_PORT",
#   "LAB_DB_USER",
#   "LAB_DB_URL",
# ]

# [scopes.farm]
# secrets = [
#   "FARM_DB_DATABASE",
#   "FARM_DB_HOST",
#   "FARM_DB_PASS",
#   "FARM_DB_PORT",
#   "FARM_DB_USER",
#   "FARM_DB_URL",
# ]
